apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MYSQL_USER: {{ .Env.MYSQL_USER | base64encode }}
  MYSQL_PASSWORD: {{ .Env.MYSQL_PASSWORD | base64encode }}
  MYSQL_DATABASE: {{ .Env.MYSQL_DATABASE | base64encode }}
  BUILD_NUMBER: {{ .Env.BUILD_NUMBER | base64encode }}
